# Generated by Django 5.0.2 on 2026-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Овог')),
                ('first_name', models.CharField(max_length=50, verbose_name='Нэр')),
                ('age', models.PositiveIntegerField(verbose_name='Нас')),
                ('gender', models.CharField(choices=[('M', 'Эр'), ('F', 'Эм')], max_length=1, verbose_name='Хүйс')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Утасны дугаар')),
                ('course', models.PositiveIntegerField(verbose_name='Курс')),
                ('major', models.CharField(max_length=100, verbose_name='Мэргэжил')),
                ('student_code', models.CharField(max_length=20, unique=True, verbose_name='Оюутны код')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Чадварууд')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэгдсэн огноо')),
            ],
            options={
                'verbose_name': 'Оюутан',
                'verbose_name_plural': 'Оюутнууд',
                'db_table': 'sandboxDB',
            },
        ),
    ]
