# Generated by Django 5.0.2 on 2026-03-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
