# Generated by Django 6.0.3 on 2026-03-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Төслийн нэр')),
                ('description', models.TextField(verbose_name='Төслийн тайлбар')),
                ('status', models.CharField(choices=[('planning', 'Төлөвлөж байгаа'), ('ongoing', 'Хийгдэж байгаа'), ('completed', 'Дууссан')], default='planning', max_length=20, verbose_name='Төслийн төлөв')),
            ],
            options={
                'verbose_name': 'Төсөл',
                'verbose_name_plural': 'Төслүүд',
                'db_table': 'projects',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.PositiveIntegerField(verbose_name='Курс')),
                ('joined_at', models.DateField(verbose_name='Клубт элссэн огноо')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Товч танилцуулга')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_member', to='AppOne.user', verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Клубийн гишүүн',
                'verbose_name_plural': 'Клубийн гишүүд',
                'db_table': 'club_members',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('leader', 'Багийн ахлагч'), ('backend', 'Backend хөгжүүлэгч'), ('frontend', 'Frontend хөгжүүлэгч'), ('fullstack', 'Full Stack хөгжүүлэгч'), ('designer', 'UI/UX дизайнер'), ('tester', 'Тестлэгч'), ('pm', 'Төслийн менежер'), ('other', 'Бусад')], max_length=20, verbose_name='Үүрэг')),
                ('responsibility', models.TextField(blank=True, null=True, verbose_name='Хариуцсан ажил')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='AppOne.clubmember', verbose_name='Гишүүн')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='AppOne.project', verbose_name='Төсөл')),
            ],
            options={
                'verbose_name': 'Төслийн гишүүн',
                'verbose_name_plural': 'Төслийн гишүүд',
                'db_table': 'project_members',
                'unique_together': {('member', 'project', 'role')},
            },
        ),
    ]
