# Generated by Django 6.0.3 on 2026-03-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0004_user_email_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='И-мэйл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Нууц үг'),
        ),
    ]
